openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://localhost/php-files/contacts/
paths:

  /send/{senderID}/{receiverID}/{message}/:
    post:
      parameters:
      - name: senderID
        in: path
        description: Sender ID
        required: true
        schema:
          type: string
          example: 0769878653
      - name: receiverID
        in: path
        description: Revicer ID
        required: true
        schema:
          type: string
          example: 0769002233
      - name: message
        in: path
        description: Sender ID
        required: true
        schema:
          type: string
          example: call
      tags:
        - call
      summary: Starts a call from the given id to the given recieverID.
      responses:
        '200':
          description: Successful operation

  /recive/{senderID}/:
    post:
      parameters:
      - name: senderID
        in: path
        description: User ID
        required: true
        schema:
          type: string
          example: 0769878653    
      tags:
        - call
      summary: End a call from the given id to the given recieverID.
      responses:
        '200':
          description: Successful operation