openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://localhost/php-files/contacts/
paths:

  /call/{senderID}{receiverID}/started:
    post:
      parameters:
      - name: senderID
        in: path
        description: Sender ID
        required: true
        schema:
          type: string
          example: 0769878653
      - name: receiverID
        in: path
        description: Revicer ID
        required: true
        schema:
          type: string
          example: 0769002233
      tags:
        - call
      summary: Starts a call from the given id to the given recieverID.
      responses:
        '200':
          description: Successful operation

  /call/{senderID}{receiverID}/ended:
    post:
      parameters:
      - name: senderID
        in: path
        description: User ID
        required: true
        schema:
          type: string
          example: 0769878653
      - name: receiverID
        in: path
        description: Revicer ID
        required: true
        schema:
          type: string
          example: 0769002233
        
      tags:
        - call
      summary: End a call from the given id to the given recieverID.
      responses:
        '200':
          description: Successful operation
          
  /call/{senderID}{receiverID}/accepted:
    post:
      parameters:
      - name: senderID
        in: path
        description: User ID
        required: true
        schema:
          type: string
          example: 0769878653
      - name: receiverID
        in: path
        description: Revicer ID
        required: true
        schema:
          type: string
          example: 0769002233
      tags:
        - call
      summary: Accepts a call from the given id to the given recieverID.
      responses:
        '200':
          description: Successful operation
          
  /call/{senderID}{receiverID}/rejected:
    post:
      parameters:
      - name: senderID
        in: path
        description: User ID
        required: true
        schema:
          type: string
          example: 0769878653
      - name: receiverID
        in: path
        description: Revicer ID
        required: true
        schema:
          type: string
          example: 0769002233
          
      tags:
        - call
      summary: Rejects a call from the given id to the given recieverID.
      responses:
        '200':
          description: Successful operation
          
  /call/{senderID}/poll:
    get:
      parameters:
      - name: senderID
        in: path
        description: User ID
        required: true
        schema:
          type: string
          example: 0769878653
      tags:
        - call
      summary: Checks for a started call for the given ID.
      responses:
        '200':
          description: Successful operation
          